src/Method/RFC/RFC7231.php, src/Method/RFC/Status/ProposedStandard.php, test/Unit/Method/RFC/RFC7231Test.php, test/Unit/MethodTest.php
This PR
💁‍♂ For reference, see https://tools.ietf.org/html/rfc7231.
=> Enhancement: Extract interface for RFC7231

src/Method.php, src/Method/RFC/RFC5789.php, test/Unit/Method/RFC/RFC5789Test.php, test/Unit/MethodTest.php
This PR
💁‍♂ For reference, see https://tools.ietf.org/html/rfc5789.
=> Enhancement: Extract interface for RFC5789

src/Method/RFC/RFC2068.php, test/Unit/Method/RFC/RFC2068Test.php
This PR
💁‍♂ For reference, see https://tools.ietf.org/html/rfc2068.
=> Enhancement: Add interface for RFC2068

src/Method/RFC/RFC3253.php, test/Unit/Method/RFC/RFC3253Test.php
This PR
💁‍♂ For reference, see https://tools.ietf.org/html/rfc3253.
=> Enhancement: Add interface for RFC3253

src/Method/RFC/RFC3744.php, test/Unit/Method/RFC/RFC3744Test.php
This PR
💁‍♂ For reference, see https://tools.ietf.org/html/rfc3744.
=> Enhancement: Add interface for RFC3744

src/Method/RFC/RFC4437.php, src/Method/RFC/Status/Experimental.php, test/Unit/Method/RFC/RFC4437Test.php
This PR
💁‍♂ For reference, see https://tools.ietf.org/html/rfc4437.
=> Enhancement: Add interface for RFC4437

src/Method/RFC/RFC4791.php, test/Unit/Method/RFC/RFC4791Test.php
This PR
💁‍♂ For reference, see https://tools.ietf.org/html/rfc4791.
=> Enhancement: Add interface for RFC4791

src/Method/RFC/RFC4918.php, test/Unit/Method/RFC/RFC4918Test.php
This PR
💁‍♂ For reference, see https://tools.ietf.org/html/rfc4918.
=> Enhancement: Add interface for RFC4918

.github/settings.yml
=> Enhancement: Add labels

src/Method/RFC/RFC5323.php, test/Unit/Method/RFC/RFC5323Test.php
This PR
💁‍♂ For reference, see https://tools.ietf.org/html/rfc5323.
=> Enhancement: Add interface for RFC5323

src/Method/RFC/RFC5842.php, test/Unit/Method/RFC/RFC5842Test.php
This PR
💁‍♂ For reference, see https://tools.ietf.org/html/rfc5842.
=> Enhancement: Add interface for RFC5842

src/Method/RFC/RFC7540.php, test/Unit/Method/RFC/RFC7540Test.php
This PR
💁‍♂ For reference, see https://tools.ietf.org/html/rfc7540.
=> Enhancement: Add interface for RFC7540

src/Method/Vendor/SquidCache.php, test/Unit/Method/Vendor/SquidCacheTest.php
This PR
💁‍♂ For reference, see https://wiki.squid-cache.org/FrontPage.
=> Enhancement: Add interface for Squid cache request methods

src/Method/Vendor/VarnishCache.php, test/Unit/Method/Vendor/VarnishCacheTest.php
This PR
💁‍♂ For reference, see https://varnish-cache.org/docs/index.html.
=> Enhancement: Add interface for Varnish cache request methods

src/Method.php
=> Enhancement: Wrap extended interfaces

src/Method/WebDav.php, test/Unit/Method/WebDavTest.php
=> Enhancement: Aggregate HTTP methods related to WebDAV

README.md
=> Enhancement: List php-fig/http-message-util

.dependabot/config.yml, .github/stale.yml, .github/workflows/stale.yml, .travis.yml, Makefile, phpstan.neon
=> Enhancement: Synchronize project tooling configuration with localheinz/php-library-template

.dependabot/config.yml, .github/CONTRIBUTING.md, .github/settings.yml, .github/workflows/continuous-integration.yml, .github/workflows/stale.yml, Makefile, README.md, composer.json, composer.lock, phpstan-baseline.neon, phpstan.neon, test/AutoReview/phpunit.xml, test/Integration/phpunit.xml
=> Enhancement: Synchronize with ergebnis/php-library-template

composer.json, composer.lock, phpstan.neon
=> Enhancement: Update phpstan/phpstan and friends

composer.json, composer.lock
=> Enhancement: Update vimeo/psalm and friends

README.md
=> Enhancement: Add badge for Triage workflow

.github/settings.yml, .github/workflows/integrate.yaml, CHANGELOG.md, composer.json, composer.lock
=> Fix: Drop support for PHP 7.2

Makefile
=> Fix: Reference

.php-cs-fixer.php
=> Enhancement: Use `Php73` rule set

.editorconfig, .github/workflows/integrate.yaml, .github/workflows/merge.yaml, .github/workflows/release.yaml, .github/workflows/renew.yaml, .github/workflows/triage.yaml, .phive/phars.xml, .php-cs-fixer.php, composer.json, composer.lock, psalm-baseline.xml, rector.php, test/Unit/Method/Rfc/Rfc2068Test.php, test/Unit/Method/Rfc/Rfc3253Test.php, test/Unit/Method/Rfc/Rfc3648Test.php, test/Unit/Method/Rfc/Rfc3744Test.php, test/Unit/Method/Rfc/Rfc4437Test.php, test/Unit/Method/Rfc/Rfc4791Test.php, test/Unit/Method/Rfc/Rfc4918Test.php, test/Unit/Method/Rfc/Rfc5323Test.php, test/Unit/Method/Rfc/Rfc5789Test.php, test/Unit/Method/Rfc/Rfc5842Test.php, test/Unit/Method/Rfc/Rfc7231Test.php, test/Unit/Method/Rfc/Rfc7540Test.php, test/Unit/Method/Vendor/SquidCacheTest.php, test/Unit/Method/Vendor/VarnishCacheTest.php, test/Unit/phpunit.xml
=> Enhancement: Synchronize with `ergebnis/php-package-template`

.github/settings.yml
GitHub renamed the probot repository
=> Update URL in `settings.yml`
